@host=https://api-gateway-app.wonderfulwave-67ac4af3.eastus.azurecontainerapps.io/

POST {{host}}/authentication/login/
Content-Type: application/json

{
    "email": "admin@documentally.com",
    "password": "admin"
}