@host=https://api-gateway-app.wonderfulwave-67ac4af3.eastus.azurecontainerapps.io

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "Admin",
    "LastName": "Admin",
    "email": "admin@tekchallenge.com",
    "password": "admin"
}